
version: "{branch}.build.{build}"

image: Visual Studio 2017

branches:
  only:
    - master

cache:
  - c:\build-cache

environment:
  SRC_BUILD_FOLDER: c:\build-cache

platform:
  - x86

build: false

install:
    - echo start
    - cd %APPVEYOR_BUILD_FOLDER%
    - cd ..
    - echo download php
    - ps: Invoke-WebRequest https://windows.php.net/downloads/releases/archives/php-7.1.15-Win32-VC14-x86.zip -OutFile ${env:APPVEYOR_BUILD_FOLDER}\..\php.zip
    - 'mkdir php && mv php.zip php\php.zip && cd php'
    - 7z.exe x php.zip | FIND /V "ing "
    - cd ..

    - echo download nginx 
    - ps: Invoke-WebRequest http://nginx.org/download/nginx-1.10.3.zip -OutFile ${env:APPVEYOR_BUILD_FOLDER}\..\nginx.zip
    - 'mkdir nginx && mv nginx.zip nginx\nginx.zip && cd nginx'
    - 7z.exe x nginx.zip | FIND /V "ing "
    - cd ..

test: off